# Copyright 2026 DataMasque Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this library except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0

from importlib.metadata import version

from datamasque.client.dmclient import DataMasqueClient, FileOrContent
from datamasque.client.exceptions import (
    AsyncRulesetGenerationInProgressError,
    DataMasqueApiError,
    DataMasqueException,
    DataMasqueIfmError,
    DataMasqueNotReadyError,
    DataMasqueTransportError,
    DataMasqueUserError,
    FailedToStartError,
    IfmAuthError,
    InvalidDiscoveryConfigError,
    InvalidLibraryError,
    InvalidRulesetError,
    RunNotCancellableError,
)
from datamasque.client.ifm import DataMasqueIfmClient
from datamasque.client.models.connection import (
    AzureConnectionConfig,
    ConnectionConfig,
    ConnectionId,
    DatabaseConnectionConfig,
    DatabaseType,
    DatabricksConnectionConfig,
    DynamoConnectionConfig,
    FileConnectionConfig,
    MongoConnectionConfig,
    MountedShareConnectionConfig,
    MssqlLinkedServerConnectionConfig,
    S3ConnectionConfig,
    SnowflakeConnectionConfig,
    SnowflakeStageLocation,
    SseConfig,
    SseSelection,
)
from datamasque.client.models.data_selection import (
    HashColumnsTableConfig,
    JsonPath,
    Locator,
    SelectedColumns,
    SelectedData,
    SelectedFileData,
    UserSelection,
)
from datamasque.client.models.discovery import (
    ConstraintColumns,
    DiscoveryMatch,
    FileDataDiscoveryOptions,
    FileDataDiscoveryRequest,
    FileDataDiscoveryV2Request,
    FileDiscoveryFile,
    FileDiscoveryLocatorResult,
    FileDiscoveryMatch,
    FileDiscoveryResult,
    FileFilter,
    FileFilterMatchAgainst,
    FileRulesetGenerationRequest,
    ForeignKeyRef,
    InDataDiscoveryConfig,
    InDataDiscoveryRule,
    ReferencingForeignKey,
    RulesetGenerationRequest,
    SchemaDiscoveryColumn,
    SchemaDiscoveryPage,
    SchemaDiscoveryRequest,
    SchemaDiscoveryResult,
    SchemaDiscoveryV2Request,
    TableConstraints,
)
from datamasque.client.models.discovery_config import DiscoveryConfig, DiscoveryConfigId
from datamasque.client.models.dm_instance import DataMasqueInstanceConfig
from datamasque.client.models.files import (
    DataMasqueFile,
    FileId,
    OracleWalletFile,
    SeedFile,
    SnowflakeKeyFile,
    SslZipFile,
)
from datamasque.client.models.ifm import (
    DataMasqueIfmInstanceConfig,
    IfmLog,
    IfmMaskRequest,
    IfmMaskResult,
    IfmRulesetPlanRef,
    IfmTokenInfo,
    RulesetPlan,
    RulesetPlanCreateRequest,
    RulesetPlanOptions,
    RulesetPlanPartialUpdateRequest,
    RulesetPlanUpdateRequest,
)
from datamasque.client.models.license import LicenseInfo, SwitchableLicenseMetadata
from datamasque.client.models.ruleset import Ruleset, RulesetId, RulesetType
from datamasque.client.models.ruleset_library import RulesetLibrary, RulesetLibraryId
from datamasque.client.models.runs import (
    MaskingRunOptions,
    MaskingRunRequest,
    MaskType,
    RunConnectionRef,
    RunId,
    RunInfo,
    UnfinishedRun,
)
from datamasque.client.models.status import AsyncRulesetGenerationTaskStatus, MaskingRunStatus, ValidationStatus
from datamasque.client.models.user import User, UserId, UserRole

__version__ = version("datamasque-python")

__all__ = [
    "AsyncRulesetGenerationInProgressError",
    "AsyncRulesetGenerationTaskStatus",
    "AzureConnectionConfig",
    "ConnectionConfig",
    "ConnectionId",
    "ConstraintColumns",
    "DataMasqueApiError",
    "DataMasqueClient",
    "DataMasqueException",
    "DataMasqueFile",
    "DataMasqueIfmClient",
    "DataMasqueIfmError",
    "DataMasqueIfmInstanceConfig",
    "DataMasqueInstanceConfig",
    "DataMasqueNotReadyError",
    "DataMasqueTransportError",
    "DataMasqueUserError",
    "DatabaseConnectionConfig",
    "DatabaseType",
    "DatabricksConnectionConfig",
    "DiscoveryConfig",
    "DiscoveryConfigId",
    "DiscoveryMatch",
    "DynamoConnectionConfig",
    "FailedToStartError",
    "FileConnectionConfig",
    "FileDataDiscoveryOptions",
    "FileDataDiscoveryRequest",
    "FileDataDiscoveryV2Request",
    "FileDiscoveryFile",
    "FileDiscoveryLocatorResult",
    "FileDiscoveryMatch",
    "FileDiscoveryResult",
    "FileFilter",
    "FileFilterMatchAgainst",
    "FileId",
    "FileOrContent",
    "FileRulesetGenerationRequest",
    "ForeignKeyRef",
    "HashColumnsTableConfig",
    "IfmAuthError",
    "IfmLog",
    "IfmMaskRequest",
    "IfmMaskResult",
    "IfmRulesetPlanRef",
    "IfmTokenInfo",
    "InDataDiscoveryConfig",
    "InDataDiscoveryRule",
    "InvalidDiscoveryConfigError",
    "InvalidLibraryError",
    "InvalidRulesetError",
    "JsonPath",
    "LicenseInfo",
    "Locator",
    "MaskType",
    "MaskingRunOptions",
    "MaskingRunRequest",
    "MaskingRunStatus",
    "MongoConnectionConfig",
    "MountedShareConnectionConfig",
    "MssqlLinkedServerConnectionConfig",
    "OracleWalletFile",
    "ReferencingForeignKey",
    "Ruleset",
    "RulesetGenerationRequest",
    "RulesetId",
    "RulesetLibrary",
    "RulesetLibraryId",
    "RulesetPlan",
    "RulesetPlanCreateRequest",
    "RulesetPlanOptions",
    "RulesetPlanPartialUpdateRequest",
    "RulesetPlanUpdateRequest",
    "RulesetType",
    "RunConnectionRef",
    "RunId",
    "RunInfo",
    "RunNotCancellableError",
    "S3ConnectionConfig",
    "SchemaDiscoveryColumn",
    "SchemaDiscoveryPage",
    "SchemaDiscoveryRequest",
    "SchemaDiscoveryResult",
    "SchemaDiscoveryV2Request",
    "SeedFile",
    "SelectedColumns",
    "SelectedData",
    "SelectedFileData",
    "SnowflakeConnectionConfig",
    "SnowflakeKeyFile",
    "SnowflakeStageLocation",
    "SseConfig",
    "SseSelection",
    "SslZipFile",
    "SwitchableLicenseMetadata",
    "TableConstraints",
    "UnfinishedRun",
    "User",
    "UserId",
    "UserRole",
    "UserSelection",
    "ValidationStatus",
]
